version: '3.8'
services:
  keycult-monitor:
    build: .
    container_name: keycult-monitor
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
      - CHECK_INTERVAL=${CHECK_INTERVAL:-1}
      - HEARTBEAT_INTERVAL=${HEARTBEAT_INTERVAL:-10}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped 